"""Shared HTML report building blocks.

Prior to v26 there were three independent HTML report generators
(``cockpit.build_enhanced_html_report``, ``report_builder.build_sectioned_report``
and ``batch.build_batch_html_report``), each carrying its own copy of a
near-identical inline stylesheet. This module is the single place that owns
the report look-and-feel and the small set of HTML fragments (tables, stat
cards, bullet lists, figures) that every report assembles from. Each
specific report module now only supplies *content* and calls
:func:`render_document` to wrap it.
"""

from __future__ import annotations

import html
from typing import Iterable

import pandas as pd

#: Single shared stylesheet for every exported report (Report, Report
#: Builder, Batch Report). Tweak once, every report updates.
REPORT_CSS = """
body { font-family: Arial, sans-serif; margin: 2rem; color: #111827; }
h1 { color: #0f172a; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
h2 { color: #0f172a; margin-top: 2rem; }
.section { margin-bottom: 1.5rem; }
.cards { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem; margin: 1rem 0; }
.card { border: 1px solid #d1d5db; border-radius: 10px; padding: 0.8rem; background: #f8fafc; }
.card .label { color: #64748b; font-size: 0.85rem; }
.card .value { font-size: 1.35rem; font-weight: bold; margin-top: 0.25rem; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.85rem; }
th, td { border: 1px solid #d1d5db; padding: 0.35rem 0.45rem; text-align: right; }
th { background: #e5e7eb; }
td:first-child, th:first-child { text-align: left; }
.note { background: #eff6ff; border-left: 4px solid #2563eb; padding: 0.75rem; }
.figure { margin: 1.25rem 0; border: 1px solid #e5e7eb; padding: .5rem; border-radius: 8px; }
.footer { margin-top: 2rem; color: #94a3b8; font-size: 0.8rem; border-top: 1px solid #e5e7eb; padding-top: 0.5rem; }
"""


def render_table(df: pd.DataFrame | None, empty: str = "No data available.") -> str:
    """Render a DataFrame as an HTML table, or an escaped placeholder."""
    if df is None or df.empty:
        return f"<p>{html.escape(empty)}</p>"
    return df.to_html(index=False, escape=False)


def render_list(items: Iterable[object] | None, empty: str = "Nothing to show.") -> str:
    """Render an iterable of strings as a bullet list, or a placeholder."""
    items = list(items or [])
    if not items:
        return f"<p>{html.escape(empty)}</p>"
    return "<ul>" + "".join(f"<li>{html.escape(str(item))}</li>" for item in items) + "</ul>"


def render_cards(cards: list[tuple[str, object]]) -> str:
    """Render a list of (label, value) pairs as a small grid of stat cards."""
    if not cards:
        return ""
    body = "".join(
        f'<div class="card"><div class="label">{html.escape(str(label))}</div>'
        f'<div class="value">{html.escape(str(value))}</div></div>'
        for label, value in cards
    )
    return f'<div class="cards">{body}</div>'


def render_note(text: str) -> str:
    return f'<p class="note">{html.escape(str(text))}</p>'


def render_figures(figures: Iterable[str] | None) -> str:
    figures = list(figures or [])
    if not figures:
        return "<p>No figures selected.</p>"
    return "".join(f"<div class='figure'>{fig}</div>" for fig in figures)


def render_document(title: str, body_sections: list[tuple[str, str]], heading: str | None = None) -> bytes:
    """Wrap a list of (section_title, section_html) pairs in the shared template.

    ``heading`` overrides the visible <h1>; ``title`` is always used for
    <title>. Pass an empty section title ("") to render content without a
    surrounding <h2> (used for the top intro note / cards block).
    """
    heading = heading or title
    parts = []
    for name, content in body_sections:
        if name:
            parts.append(f'<div class="section"><h2>{html.escape(name)}</h2>{content}</div>')
        else:
            parts.append(f'<div class="section">{content}</div>')

    doc = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>{REPORT_CSS}</style>
</head>
<body>
<h1>{html.escape(heading)}</h1>
{''.join(parts)}
<div class="footer">Generated by .out Output Viewer.</div>
</body>
</html>"""
    return doc.encode("utf-8")
